#!/usr/bin/env bash
# Find the process ID of 4-to_infinity_and_beyond

pid=$(pgrep -f '4-to_infinity_and_beyond')

if [ -n "$pid" ]; then
	kill -SIGTERM "$pid"
	echo "Terminated"
else
	echo "Process not found"
fi

