#!/usr/bin/env bash
# This script displays username, user id, and home directory path for users in /etc/passwd

while IFS=':' read -r username _ uid _ _ home_dir _; do
    echo "$username:$uid:$home_dir"
done < /etc/passwd
