#!/usr/bin/env bash
# This script tells the story of each user in /etc/passwd

while IFS=':' read -r username _ uid gid _ home_dir shell; do
    echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
