#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, displays occurrence number, and sorts the data

awk -F' ' '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -nr
