#!/usr/bin/env bash

# Checks if script is runnig as root
if [ "$EUID" -ne 0 ]; then
	echo "Please run as root"
	exit 1
fi

# Backup the original hosts file
cp /etc/hosts /etc/host_tmp

# Update localhost to resolve to 127.0.0.2
sed -i "s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g" /etc/hosts

# Update facebook.com to resolve to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Output success message
echo "Hosts file updated successfully."

# Print instruction to revert changesecho 
echo "To revert changes, run: sudo mv /etc/hosts.bak /etc/hosts"
